### ISSUE TITLE
feat: AWS distinguish customer-managed encryption keys for more services

### ISSUE THREAD

**Issue by tom-dalton-fanduel** [aquasecurity/tfsec#1819]
**Is your feature request related to a problem? Please describe.**
I would like to ensure AWS resources are using at-rest encryption, but I don't want to use customer-managed keys, I am happy to use AWS-managed keys.

I already can do this for some resource types - e.g. EBS volumes (https://github.com/aquasecurity/tfsec/tree/master/docs/checks/aws/ebs) have two checks - `enable-volume-encryption` and `encryption-customer-key`. I can configure tfsec to care about the first but not about the second - great!

However, other resources (e.g. SQS https://github.com/aquasecurity/tfsec/blob/8d6f30e5ab5deb0ff4f37e4a72454d08a81cbad6/docs/checks/aws/sqs/enable-queue-encryption/index.md) do not allow this distinction. SQS has a single catch-all `enable-queue-encryption` check, that requires both at-rest encryption and that a customer-managed key is used. This means I either have to ignore encryption warnings entirely for SQS, or I need to use customer-managed keys to get rid of the warning.

**Describe the solution you'd like**
It would be great to have the 2 different checks like EBS does across all applicable AWS resources.

**Describe alternatives you've considered**
I'm not sure what alternative solutions might be possible.

**Additional context**
-

**Comment by nikpivkin** [comment]
Hi @tom-dalton-fanduel !

The `enable-queue-encryption` rule is triggered if you do not have server-side encryption enabled and `kms_master_key_id` is not specified. If the argument `sqs_managed_sse_enabled` is used, then SSE-SQS is enabled, if the argument `kms_master_key_id` is specified, then SSE_KMS is enabled. Therefore, it does not make sense to split this rule into two, since these are mutually exclusive parameters.

Ref:
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#server-side-encryption-sse
- https://github.com/terraform-aws-modules/terraform-aws-sqs/blob/master/main.tf#L24

**Comment by nikpivkin** [comment]
Hi @tom-dalton-fanduel !

The rule [ADV-AWS-0096](https://avd.aquasec.com/misconfig/aws/sqs/avd-aws-0096/#Terraform) cannot be divided into two, since `sqs_managed_sse_enabled` and `kms_master_key_id` are mutually exclusive arguments and both enable SSE. But `sqs_managed_sse_enabled` uses SQS-managed encryption keys, and `kms_master_key_id uses`. KMS.https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#server-side-encryption-sse

/cc @simar7
